<?xml version="1.0" encoding="utf-8"?><Database Name="ConceptTest" Class="DataClassesConceptTestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLSERVER2008R2;Initial Catalog=ConceptTest;Integrated Security=True" SettingsObjectName="LINQ.Properties.Settings" SettingsPropertyName="ConceptTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.CustomersByCity" Method="CustomersByCity">
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="CustomersByCityResult">
      <Column Name="CustomerId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>